#!/usr/bin/env node
'use strict';

/**
 * Socket.IO load test for the live quiz server.
 *
 * Spins up N simulated player clients + 1 host + 1 board observer, drives the
 * full quiz end-to-end, and reports:
 *   - drop rate (attempted vs. succeeded answers)
 *   - per-question answer-ack latency (p50, p95, p99, max)
 *   - reveal latency (host:reveal → state:reveal on the board socket)
 *   - answer-count event throughput
 *   - whether the realistic answer-time distribution actually landed
 *
 * Pass/fail (event-day SLOs):
 *   - Zero dropped answers
 *   - Max reveal latency < 3000 ms
 *
 * Usage (from /opt/quiz/tools after `npm install`):
 *
 *   node loadtest.js \
 *     --url http://localhost:3000 \
 *     --token "$HOST_TOKEN" \
 *     --domain example.com \
 *     --players 2500
 *
 * The HOST_TOKEN is whatever was generated by deploy/install.sh — find it in
 * /etc/quiz/quiz.env (root-readable only).
 */

const { io } = require('socket.io-client');

// =====================================================================
// CONFIG
// =====================================================================

const args = parseArgs(process.argv.slice(2));
const URL = args.url || 'http://localhost:3000';
const TOKEN = args.token || process.env.HOST_TOKEN || '';
const DOMAIN = args.domain || 'example.com';
const N_PLAYERS = parseInt(args.players || '2500', 10);

// Connection ramp-up: open this many sockets per second. 200/sec means 12.5s
// to fully connect 2500 — gentle enough not to overwhelm the OS file table on
// either end, fast enough not to dominate test runtime.
const RAMP_RATE = parseInt(args['ramp-rate'] || '200', 10);

// 70% of players "answer late" (in the last 3 seconds of the timer);
// 30% answer at some point earlier. This matches real quiz behavior much
// better than uniform random and is the worst case for the throttled
// answerCount broadcaster.
const ANSWER_LATE_FRACTION = 0.7;
const LATE_WINDOW_MS = 3000;

// SLOs from the brief
const SLO_DROP_RATE = 0;             // zero drops allowed
const SLO_REVEAL_LATENCY_MS = 3000;  // <3s from host:reveal to state:reveal

if (!TOKEN) {
  console.error('Missing --token (or HOST_TOKEN env var).');
  console.error('Find the token in /etc/quiz/quiz.env on the VM.');
  process.exit(2);
}

console.log('============================================================');
console.log(' Quiz Load Test');
console.log('============================================================');
console.log(`URL:           ${URL}`);
console.log(`Players:       ${N_PLAYERS}`);
console.log(`Email domain:  @${DOMAIN}`);
console.log(`Ramp:          ${RAMP_RATE}/sec`);
console.log(`Late fraction: ${ANSWER_LATE_FRACTION * 100}% answer in last ${LATE_WINDOW_MS}ms`);
console.log('============================================================\n');

// =====================================================================
// STATE
// =====================================================================

/** @type {Array<{ socket: any, email: string, joined: boolean, idx: number }>} */
const players = [];

let host = null;        // moderator socket
let board = null;       // observer (board role) — receives state:reveal etc.

const stats = { perQuestion: [], totalDuration: 0 };

// =====================================================================
// HELPERS
// =====================================================================

function makeEmail(i) { return `loadtest-${i.toString().padStart(5, '0')}@${DOMAIN}`; }
function wait(ms) { return new Promise((r) => setTimeout(r, ms)); }
function pct(arr, p) {
  if (!arr.length) return 0;
  const sorted = [...arr].sort((a, b) => a - b);
  return sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * p))];
}
function realisticAnswerDelay(durationMs) {
  // Two-mode: late cluster, or earlier uniform.
  const lateWindow = Math.min(LATE_WINDOW_MS, durationMs * 0.3);
  if (Math.random() < ANSWER_LATE_FRACTION) {
    // Late: uniform in (durationMs - lateWindow, durationMs - 200)
    return durationMs - lateWindow + Math.random() * (lateWindow - 200);
  }
  // Early: uniform in (500, durationMs - lateWindow)
  return 500 + Math.random() * (durationMs - lateWindow - 500);
}
function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const k = a.slice(2);
      const v = argv[i + 1];
      if (v && !v.startsWith('--')) { out[k] = v; i++; }
      else { out[k] = true; }
    }
  }
  return out;
}

// =====================================================================
// CONNECT HOST + BOARD
// =====================================================================

async function setupControlSockets() {
  console.log('[setup] connecting host + board observers...');
  host = io(URL, {
    transports: ['websocket'],
    auth: { role: 'host', token: TOKEN },
    reconnection: false,
  });
  board = io(URL, {
    transports: ['websocket'],
    auth: { role: 'board' },
    reconnection: false,
  });
  await Promise.all([
    new Promise((res, rej) => {
      host.once('connect', res);
      host.once('connect_error', (e) => rej(new Error('host connect_error: ' + e.message)));
      host.once('error', (e) => rej(new Error('host server error: ' + (e && e.message))));
      setTimeout(() => rej(new Error('host connect timeout')), 8000);
    }),
    new Promise((res, rej) => {
      board.once('connect', res);
      board.once('connect_error', (e) => rej(new Error('board connect_error: ' + e.message)));
      setTimeout(() => rej(new Error('board connect timeout')), 8000);
    }),
  ]);
  console.log('[setup] host + board connected.');
}

// =====================================================================
// CONNECT PLAYERS
// =====================================================================

async function connectPlayers() {
  console.log(`[players] connecting ${N_PLAYERS} clients...`);
  const startMs = Date.now();
  let joined = 0;
  let connectErrs = 0;

  for (let i = 0; i < N_PLAYERS; i++) {
    const email = makeEmail(i);
    const sock = io(URL, {
      transports: ['websocket'],
      auth: { role: 'player' },
      reconnection: false,
    });
    const player = { socket: sock, email, joined: false, idx: i };
    players.push(player);

    sock.on('connect', () => {
      sock.emit('player:join', { email }, (ack) => {
        if (ack && ack.ok) {
          player.joined = true;
          joined++;
        }
      });
    });
    sock.on('connect_error', () => { connectErrs++; });

    if ((i + 1) % RAMP_RATE === 0) {
      await wait(1000);
      process.stdout.write(`  [${i + 1}/${N_PLAYERS}] connected, ${joined} joined, ${connectErrs} errors\n`);
    }
  }

  // Give straggler joins time to ack.
  console.log('[players] waiting for joins to settle...');
  const deadline = Date.now() + 15000;
  while (Date.now() < deadline && joined < N_PLAYERS) {
    await wait(500);
  }
  console.log(`[players] joined ${joined} / ${N_PLAYERS} in ${((Date.now() - startMs) / 1000).toFixed(1)}s`);
  if (connectErrs > 0) console.warn(`[players] ${connectErrs} connect errors during ramp`);
  return joined;
}

// =====================================================================
// RUN ONE QUESTION
// =====================================================================

async function runQuestion() {
  // Listen for the next question on the board socket (broadcasts go to everyone).
  const qPromise = new Promise((resolve) => board.once('state:question', resolve));

  // Trigger the host:advance.
  await new Promise((resolve, reject) => {
    host.emit('host:advance', {}, (ack) => {
      if (!ack || !ack.ok) reject(new Error('host:advance failed: ' + (ack && ack.error)));
      else resolve();
    });
  });
  const q = await qPromise;
  const durationMs = q.endsAt - q.startsAt;
  console.log(`\n[Q${q.index + 1}/${q.total}] "${q.text}" — ${durationMs}ms timer`);

  const qStat = {
    qIndex: q.index,
    durationMs,
    attempted: 0,
    succeeded: 0,
    rejected: 0,
    timedOut: 0,
    rejectReasons: {},
    ackLatencies: [],
    answerCountEvents: 0,
    answerCountFinal: false,
    revealLatencyMs: null,
    arrivalTimes: [],   // ms after startsAt — for distribution histogram
  };

  // Track state:answerCount throughput on the board socket.
  const onAnswerCount = (a) => {
    qStat.answerCountEvents++;
    if (a && a.final) qStat.answerCountFinal = true;
  };
  board.on('state:answerCount', onAnswerCount);

  // Schedule each joined player's answer.
  const scheduleStart = Date.now();
  const sendPromises = [];
  let scheduled = 0;
  for (const p of players) {
    if (!p.joined) continue;
    const delay = realisticAnswerDelay(durationMs);
    const option = Math.floor(Math.random() * 4);
    scheduled++;
    sendPromises.push(new Promise((resolve) => {
      let resolved = false;
      const finish = () => { if (!resolved) { resolved = true; resolve(); } };
      setTimeout(() => {
        const t0 = Date.now();
        qStat.attempted++;
        qStat.arrivalTimes.push(t0 - scheduleStart);
        p.socket.emit('player:answer', { qIndex: q.index, option }, (ack) => {
          const lat = Date.now() - t0;
          qStat.ackLatencies.push(lat);
          if (ack && ack.ok) {
            qStat.succeeded++;
          } else {
            qStat.rejected++;
            const reason = (ack && ack.error) || 'no-ack';
            qStat.rejectReasons[reason] = (qStat.rejectReasons[reason] || 0) + 1;
          }
          finish();
        });
        // Fail-safe: if no ack arrives within 5s, count as a timeout.
        setTimeout(() => {
          if (!resolved) qStat.timedOut++;
          finish();
        }, 5000);
      }, delay);
    }));
  }
  console.log(`[Q${q.index + 1}] scheduled ${scheduled} answers`);

  // Wait until either everyone's settled OR the timer + a generous tail elapsed.
  await Promise.race([
    Promise.all(sendPromises),
    wait(durationMs + 8000),
  ]);

  // Pause briefly so server's auto-close fires before we reveal (otherwise
  // we'd take the early-reveal branch which is fine but less realistic).
  const remainingTimer = q.endsAt - Date.now();
  if (remainingTimer > 0) await wait(remainingTimer + 500);
  await wait(500);

  // Trigger reveal and time it from emit to board's state:reveal.
  const revealOnBoard = new Promise((resolve) => board.once('state:reveal', resolve));
  const revealStartMs = Date.now();
  await new Promise((resolve, reject) => {
    host.emit('host:reveal', {}, (ack) => {
      if (!ack || !ack.ok) reject(new Error('host:reveal failed: ' + (ack && ack.error)));
      else resolve();
    });
  });
  await revealOnBoard;
  qStat.revealLatencyMs = Date.now() - revealStartMs;

  board.off('state:answerCount', onAnswerCount);

  // Per-question report
  console.log(`[Q${q.index + 1}] attempted=${qStat.attempted} succeeded=${qStat.succeeded} rejected=${qStat.rejected} timedOut=${qStat.timedOut}`);
  if (qStat.rejected > 0) {
    console.log(`[Q${q.index + 1}] reject reasons:`, qStat.rejectReasons);
  }
  console.log(`[Q${q.index + 1}] ack latency: p50=${pct(qStat.ackLatencies, 0.5)}ms p95=${pct(qStat.ackLatencies, 0.95)}ms p99=${pct(qStat.ackLatencies, 0.99)}ms max=${qStat.ackLatencies.length ? Math.max(...qStat.ackLatencies) : 0}ms`);
  console.log(`[Q${q.index + 1}] state:answerCount events received by board: ${qStat.answerCountEvents} (final=${qStat.answerCountFinal})`);
  console.log(`[Q${q.index + 1}] reveal latency: ${qStat.revealLatencyMs}ms`);

  // Distribution sanity: did most answers actually arrive in the last 3s?
  const lateArrivals = qStat.arrivalTimes.filter((t) => t >= durationMs - LATE_WINDOW_MS).length;
  const lateActual = qStat.arrivalTimes.length ? lateArrivals / qStat.arrivalTimes.length : 0;
  console.log(`[Q${q.index + 1}] arrival distribution: ${(lateActual * 100).toFixed(0)}% in last ${LATE_WINDOW_MS}ms (target ~${ANSWER_LATE_FRACTION * 100}%)`);

  stats.perQuestion.push(qStat);
}

// =====================================================================
// MAIN
// =====================================================================

(async () => {
  const t0 = Date.now();
  await setupControlSockets();
  await connectPlayers();

  // Track when the game finishes.
  let finished = false;
  board.on('state:finished', () => { finished = true; });

  // Run questions until the server says we're done.
  let qNum = 0;
  while (!finished && qNum < 50) {
    qNum++;
    try {
      await runQuestion();
    } catch (e) {
      console.error(`Question ${qNum} failed:`, e.message);
      break;
    }
    // Small grace so state:finished can arrive after the last reveal.
    await wait(800);
  }

  stats.totalDuration = Date.now() - t0;

  // ===== Final summary =====
  console.log('\n============================================================');
  console.log(' SUMMARY');
  console.log('============================================================');
  let totalAttempted = 0, totalSucceeded = 0, totalRejected = 0, totalTimedOut = 0;
  const allRevealLatencies = [];
  const allAckLatencies = [];

  stats.perQuestion.forEach((qs) => {
    totalAttempted += qs.attempted;
    totalSucceeded += qs.succeeded;
    totalRejected  += qs.rejected;
    totalTimedOut  += qs.timedOut;
    if (qs.revealLatencyMs != null) allRevealLatencies.push(qs.revealLatencyMs);
    allAckLatencies.push(...qs.ackLatencies);
  });

  const dropped = totalRejected + totalTimedOut;
  const dropRate = totalAttempted ? dropped / totalAttempted : 0;
  const maxRevealLatency = allRevealLatencies.length ? Math.max(...allRevealLatencies) : 0;

  console.log(`Total runtime:        ${(stats.totalDuration / 1000).toFixed(1)}s`);
  console.log(`Questions run:        ${stats.perQuestion.length}`);
  console.log(`Players joined:       ${players.filter((p) => p.joined).length} / ${N_PLAYERS}`);
  console.log('');
  console.log(`Answers attempted:    ${totalAttempted}`);
  console.log(`Answers succeeded:    ${totalSucceeded}`);
  console.log(`Answers rejected:     ${totalRejected}`);
  console.log(`Answers timed out:    ${totalTimedOut}`);
  console.log(`Drop rate:            ${(dropRate * 100).toFixed(3)}%`);
  console.log('');
  console.log(`Ack latency p50:      ${pct(allAckLatencies, 0.5)}ms`);
  console.log(`Ack latency p95:      ${pct(allAckLatencies, 0.95)}ms`);
  console.log(`Ack latency p99:      ${pct(allAckLatencies, 0.99)}ms`);
  console.log(`Ack latency max:      ${allAckLatencies.length ? Math.max(...allAckLatencies) : 0}ms`);
  console.log('');
  console.log(`Reveal latency max:   ${maxRevealLatency}ms`);
  console.log(`Reveal latencies:     ${allRevealLatencies.join(', ')}ms`);
  console.log('');

  // ===== Pass/fail =====
  const passDrops  = dropRate <= SLO_DROP_RATE;
  const passReveal = maxRevealLatency < SLO_REVEAL_LATENCY_MS;
  const passed = passDrops && passReveal;

  console.log('SLO: drop rate <= 0%       ' + (passDrops  ? 'PASS' : 'FAIL'));
  console.log(`SLO: reveal latency < ${SLO_REVEAL_LATENCY_MS}ms  ` + (passReveal ? 'PASS' : 'FAIL'));
  console.log('');
  console.log(passed ? 'OVERALL: PASS' : 'OVERALL: FAIL');

  // Clean up.
  players.forEach((p) => p.socket.disconnect());
  host.disconnect();
  board.disconnect();
  await wait(500);
  process.exit(passed ? 0 : 1);
})().catch((err) => {
  console.error('\nLOAD TEST CRASHED:', err);
  console.error(err.stack);
  process.exit(2);
});
